# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016-2019 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

language: python

dist: xenial

os: linux

services:
  - docker

env:
  - REQUIREMENTS=devel
  - REQUIREMENTS=release
  - REQUIREMENTS=lowest

cache:
  - docker

install:
  - "docker build -t xrootd ."
  - "docker run -h xrootdhost -t -u root xrootd pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install coveralls pydocstyle Sphinx twine wheel"

script:
  - "docker run -h xrootdhost -t xrootd"

after_success:
  - coveralls

notifications:
  email: false
